version: '3'
services:
  vertex-download:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - '~/.config/gcloud:/root/.config/gcloud'
      - './main.py:/code/main.py'
      - './bq.py:/code/bq.py'
      - './slack.py:/code/slack.py'
      - './state.py:/code/state.py'
      - './tests:/code/tests'