
version: 2

models:

  - name: v_fishing_hours_vessel_lists
    description: "Fishing hours based on pipe2.5 vi_ssvid{_byyear}"
  - name: t_fishing_hours
    description: "Fishing effort aimed at reproducing values in products"
  - name: t_fishing_hours_pipe2_5
    description: "Fishing hours per day (pipe2.5)"
  - name: t_fishing_hours_pipe3
    description: "Fishing hours per day (pipe3)"