anomalies:
  gfw_api_delays:
      source_project: "world-fishing-827"
      source_dataset: tech_dq_monitoring
      source_table: v_scraped_api_values
      source_timestamp_column: timestamp
      source_timestamp_column_sql: timestamp
      source_forecast_column: timestamp_delay_now_hypothetical_vs_expected_delay_hour
      source_forecast_column_sql: MIN(timestamp_delay_now_hypothetical_vs_expected_delay_hour)
      period_length: day
      dimension_split: dataset
      history_start: '2025-01-31'
      refetch_recent_days: 14
      source_filter_sql: "
      date_interval = 'DAY'
      AND environment = 'prod'
      AND timestamp_delay_now_hypothetical_vs_expected_delay_hour > 0
      AND date >= first_valid_from_date"
      algorithms:
          constant_value:
              parameters:
                value: 0.5
