anomalies:
  parser_errors_daily:
      source_project: "world-fishing-827"
      source_dataset: "tech_dq_monitoring"
      source_table: "t_pipe_nmea_parsed_errors"
      source_timestamp_column: "date"
      source_timestamp_column_sql: 'TIMESTAMP(date)'
      source_forecast_column: "count"
      source_forecast_column_sql: "SUM(count)"
      period_length: "day"
      algorithms:
          mstl: 
              parameters: 
                season_length: 
                  - 365.25
                  - 7
          mean:
              parameters:
                sliding_window: 30
          median:
              parameters:
                sliding_window: 30
  parser_errors_daily_by_source:
      source_project: "world-fishing-827"
      source_dataset: "tech_dq_monitoring"
      source_table: "t_pipe_nmea_parsed_errors"
      source_timestamp_column: "date"
      source_timestamp_column_sql: 'TIMESTAMP(date)'
      source_forecast_column: "count"
      source_forecast_column_sql: "SUM(count)"
      period_length: "day"
      dimension_split: source
      source_filter_sql: "source != 'marinetraffic'"
      algorithms:
          mstl: 
              parameters: 
                season_length: 
                  - 365.25
                  - 7
          mean:
              parameters:
                sliding_window: 30
          median:
              parameters:
                sliding_window: 30
  parsed_row_count_source_daily:
      source_project: "world-fishing-827"
      source_dataset: "tech_dq_monitoring"
      source_table: "t_facts_pipe_nmea_parsed_stats_daily"
      source_timestamp_column: "date"
      source_timestamp_column_sql: 'TIMESTAMP(date)'
      source_forecast_column: "count"
      source_forecast_column_sql: "count"
      period_length: "day"
      history_start: "2022-08-23"
      source_sql: '
      SUM(count) AS value, TIMESTAMP(date) AS timestamp, value AS dimension_split_value 
      FROM `world-fishing-827.tech_dq_monitoring.t_facts_pipe_nmea_parsed_stats_daily`
      WHERE variable = "source"
      AND {current_anomaly_detection_config$source_timestamp_column_sql} IN ({missing_timestamps_sql})
      AND {current_anomaly_detection_config$source_timestamp_column_sql} NOT IN ({existing_timestamps_sql})
      AND {current_anomaly_detection_config$source_timestamp_column_sql} >= "{history_start}"
      GROUP BY timestamp, dimension_split_value
      ORDER BY timestamp, dimension_split_value
      '
      algorithms:
          mstl: 
              parameters: 
                season_length: 
                  - 365.25
                  - 7
          mean:
              parameters:
                sliding_window: 30
          median:
              parameters:
                sliding_window: 30
  parsed_row_count_receiver_type_daily:
      source_project: "world-fishing-827"
      source_dataset: "tech_dq_monitoring"
      source_table: "t_facts_pipe_nmea_parsed_stats_daily"
      source_timestamp_column: "date"
      source_timestamp_column_sql: 'TIMESTAMP(date)'
      source_forecast_column: "count"
      source_forecast_column_sql: "count"
      period_length: "day"
      history_start: "2022-08-23"
      source_sql: '
      SUM(count) AS value, TIMESTAMP(date) AS timestamp, value AS dimension_split_value 
      FROM `world-fishing-827.tech_dq_monitoring.t_facts_pipe_nmea_parsed_stats_daily`
      WHERE variable = "receiver_type"
      AND value != "unknown"
      AND {current_anomaly_detection_config$source_timestamp_column_sql} IN ({missing_timestamps_sql})
      AND {current_anomaly_detection_config$source_timestamp_column_sql} NOT IN ({existing_timestamps_sql})
      AND {current_anomaly_detection_config$source_timestamp_column_sql} >= "{history_start}"
      GROUP BY timestamp, dimension_split_value
      ORDER BY timestamp, dimension_split_value
      '
      algorithms:
          mstl: 
              parameters: 
                season_length: 
                  - 365.25
                  - 7
          mean:
              parameters:
                sliding_window: 30
          median:
              parameters:
                sliding_window: 30
  parsed_row_count_main_types_daily:
      source_project: "world-fishing-827"
      source_dataset: "tech_dq_monitoring"
      source_table: "t_facts_pipe_nmea_parsed_stats_daily"
      source_timestamp_column: "date"
      source_timestamp_column_sql: 'TIMESTAMP(date)'
      source_forecast_column: "count"
      source_forecast_column_sql: "count"
      period_length: "day"
      history_start: "2022-08-23"
      source_sql: '
      SUM(count) AS value, TIMESTAMP(date) AS timestamp, value AS dimension_split_value 
      FROM `world-fishing-827.tech_dq_monitoring.t_facts_pipe_nmea_parsed_stats_daily`
      WHERE variable = "type"
      AND {current_anomaly_detection_config$source_timestamp_column_sql} IN ({missing_timestamps_sql})
      AND {current_anomaly_detection_config$source_timestamp_column_sql} NOT IN ({existing_timestamps_sql})
      AND {current_anomaly_detection_config$source_timestamp_column_sql} >= "{history_start}"
      AND value IN ("1", "3", "5", "18", "21", "24", "27")
      GROUP BY timestamp, dimension_split_value
      ORDER BY timestamp, dimension_split_value
      '
      algorithms:
          mstl: 
              parameters: 
                season_length: 
                  - 365.25
                  - 7
          mean:
              parameters:
                sliding_window: 30
          median:
              parameters:
                sliding_window: 30
  parsed_row_count_non_main_types_daily:
      source_project: "world-fishing-827"
      source_dataset: "tech_dq_monitoring"
      source_table: "t_facts_pipe_nmea_parsed_stats_daily"
      source_timestamp_column: "date"
      source_timestamp_column_sql: 'TIMESTAMP(date)'
      source_forecast_column: "count"
      source_forecast_column_sql: "count"
      period_length: "day"
      history_start: "2022-08-23"
      source_sql: '
      SUM(count) AS value, TIMESTAMP(date) AS timestamp, value AS dimension_split_value 
      FROM `world-fishing-827.tech_dq_monitoring.t_facts_pipe_nmea_parsed_stats_daily`
      WHERE variable = "type"
      AND {current_anomaly_detection_config$source_timestamp_column_sql} IN ({missing_timestamps_sql})
      AND {current_anomaly_detection_config$source_timestamp_column_sql} NOT IN ({existing_timestamps_sql})
      AND {current_anomaly_detection_config$source_timestamp_column_sql} >= "{history_start}"
      AND NOT value IN ("1", "3", "5", "18", "21", "24", "27")
      GROUP BY timestamp, dimension_split_value
      ORDER BY timestamp, dimension_split_value
      '
      algorithms:
          mstl: 
              parameters: 
                season_length: 
                  - 365.25
                  - 7
          mean:
              parameters:
                sliding_window: 30
          median:
              parameters:
                sliding_window: 30
  pipe3_gaps:
      source_project: "global-fishing-watch"
      source_dataset: pipe_ais_v3_published
      source_table: product_events_ais_disabling
      source_timestamp_column: event_end
      source_timestamp_column_sql: TIMESTAMP_TRUNC(event_end, DAY)
      source_forecast_column: count
      source_forecast_column_sql: COUNT(*)
      period_length: day
      algorithms:
          mstl: 
              parameters: 
                season_length: 
                  - 365.25
                  - 7
          mean:
              parameters:
                sliding_window: 30
          median:
              parameters:
                sliding_window: 30
  t_world_fishing_827_queries_billed:
      source_project: "world-fishing-827"
      source_dataset: tech_dq_monitoring
      source_table: t_world_fishing_827_queries
      source_timestamp_column: date
      source_timestamp_column_sql: TIMESTAMP(date)
      source_forecast_column: total_tb_billed
      source_forecast_column_sql: SUM(total_tb_billed)
      period_length: day
      algorithms:
          mstl: 
              parameters: 
                season_length: 
                  - 365.25
                  - 7
          mean:
              parameters:
                sliding_window: 30
          median:
              parameters:
                sliding_window: 30
          constant_value:
              parameters:
                value: 300
          max:
              parameters:
                sliding_window: 30
  v_world_fishing_827_queries_billed_by_sa_non_sa:
      source_project: "world-fishing-827"
      source_dataset: tech_dq_monitoring
      source_table: v_world_fishing_827_queries
      source_timestamp_column: date
      source_timestamp_column_sql: TIMESTAMP(date)
      source_forecast_column: total_tb_billed
      source_forecast_column_sql: SUM(total_tb_billed)
      period_length: day
      dimension_split: service_account
      algorithms:
          mstl: 
              parameters: 
                season_length: 
                  - 365.25
                  - 7
          mean:
              parameters:
                sliding_window: 30
          median:
              parameters:
                sliding_window: 30
          constant_value:
              parameters:
                value: 300
          max:
              parameters:
                sliding_window: 30
  parsed_row_count_hourly:
      source_project: "world-fishing-827"
      source_dataset: tech_dq_monitoring
      source_table: v_all_partitions_latest
      source_timestamp_column: partition_hour
      source_timestamp_column_sql: TIMESTAMP(partition_hour)
      source_forecast_column: total_rows
      source_forecast_column_sql: total_rows
      period_length: hour
      history_start: "30 days"
      source_sql: '
      total_rows AS value, TIMESTAMP(partition_hour) AS timestamp, "" AS dimension_split_value
      FROM `world-fishing-827.tech_dq_monitoring.v_all_partitions_latest` 
      WHERE schema_table_name = "pipe_nmea_hourly.pipe-nmea-parsed-hourly"
      AND partition_id IS NOT NULL
      QUALIFY ROW_NUMBER() OVER (ORDER BY partition_hour DESC) > 3 --the last 3 hours might not be final yet
      ORDER BY timestamp, dimension_split_value
      '
      algorithms:
          mstl: 
              parameters: 
                season_length: 
                  - 168
                  - 24
          mean:
              parameters:
                sliding_window: 72
          median:
              parameters:
                sliding_window: 72
  gfw_api_delays:
      source_project: "world-fishing-827"
      source_dataset: tech_dq_monitoring
      source_table: v_scraped_api_values
      source_timestamp_column: timestamp
      source_timestamp_column_sql: timestamp
      source_forecast_column: timestamp_delay_now_hypothetical_vs_expected_delay_hour
      source_forecast_column_sql: MIN(timestamp_delay_now_hypothetical_vs_expected_delay_hour)
      period_length: day
      dimension_split: dataset
      history_start: '2025-01-31'
      source_filter_sql: "
      date_interval = 'DAY'
      AND environment = 'prod'
      AND timestamp_delay_now_hypothetical_vs_expected_delay_hour > 0
      AND date >= first_valid_from_date"
      algorithms:
          constant_value:
              parameters:
                value: 0.5
